### ISSUE TITLE
[Bug] : Command Is Not Copied Correctly In Helm

### ISSUE THREAD

**Issue by divyansh-prks** [microcks/microcks.io#324]
### Describe the bug

1. [Go Here](https://microcks.io/documentation/guides/installation/kind-helm/)
2. ![Image](https://github.com/user-attachments/assets/eca1bac4-6592-4e9c-b214-980ff935e8d7)
If you will copy the Command then it is also copying the output.

**Comment by Rupam-It** [comment]
![Image](https://github.com/user-attachments/assets/0224a6d6-0fd1-44e7-84fc-93213a230793)
for me it works fine btw.
1st you can create a 
cluster-kind.yml file 
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
```

then you can run this 
`kind create cluster --config=cluster-kind.yaml`
else you can point out your issue.
