### ISSUE TITLE
Allow adding co-authors to a blog post

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks.io#83]
### Reason/Context

As of today, a blog post a just one author.

### Description

We'd like to have the possibility to have co-authors.

**Comment by lbroudoux** [comment]
Now done. You can use the following markup in blog post header section in YAML:

```yaml
---
title: Microcks 1.9.1 release 🚀
[...]
params:
  coauthors:
    - "John Doe"
    - "Jane Doe"
---
```
